### ISSUE TITLE
undefined: websocket.Codec

### ISSUE THREAD

**Issue by ziong** [nu7hatch/webrocket#1]
hi,
I encountered some problems when make the webrocket, details as below:
6g  -o _go_.6 webrocket.go
webrocket.go:196: undefined: websocket.Codec
webrocket.go:215: undefined: websocket.Codec
webrocket.go:216: unknown handler field 'Codec' in struct literal
webrocket.go:274: h.Codec undefined (type _handler has no field or method Codec)
webrocket.go:283: h.Codec undefined (type *handler has no field or method Codec)
webrocket.go:375: undefined: websocket.JSON
make: *_ \* [_go_.6] Error 1

seems that there is NO Codec and JSON defined in standard package "websocket", am i missing something?
thx!

**Comment by nu7hatch** [comment]
Yes, you have to use head version or weekly release. Webrocket requires refactored version of websocket pkg which is mentioned in readme.
